import { jsPDF } from 'jspdf'

// ── Constants ──────────────────────────────────────────────────────────────────

const PAGE_W  = 210   // A4 width mm
const PAGE_H  = 297   // A4 height mm
const MARGIN  = 20    // left/right margin mm

// Label column right edge; value column left edge
const LABEL_X = MARGIN + 55  // 75mm
const VALUE_X = MARGIN + 60  // 80mm
const ROW_H   = 7            // mm per row

// ── Helpers ────────────────────────────────────────────────────────────────────

function consultType(raw) {
  if (raw === 'f2f') return 'Face-to-Face'
  if (raw === 'teleconsult') return 'Teleconsultation'
  return raw ?? '—'
}

function formatDate(dateStr) {
  if (!dateStr) return '—'
  const MONTHS = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
  ]
  const [y, mo, d] = dateStr.split('-').map(Number)
  return `${String(d).padStart(2, '0')} ${MONTHS[mo - 1]} ${y}`
}

function formatTime(timeStr) {
  if (!timeStr) return '—'
  return timeStr.slice(0, 5)
}

function today() {
  const now = new Date()
  const y   = now.getFullYear()
  const mo  = String(now.getMonth() + 1).padStart(2, '0')
  const d   = String(now.getDate()).padStart(2, '0')
  return formatDate(`${y}-${mo}-${d}`)
}

function statusLabel(status) {
  const map = {
    pending:              'Pending',
    accepted:             'Confirmed',
    reschedule_requested: 'Reschedule Requested',
    cancelled:            'Cancelled',
    rejected:             'Rejected',
  }
  return map[status] ?? status
}

// ── PDF builder primitives ─────────────────────────────────────────────────────

function makeDoc() {
  return new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
}

function drawHeader(doc, subtitle) {
  // Header bar
  doc.setFillColor(29, 64, 156)   // #1D409C
  doc.rect(0, 0, PAGE_W, 18, 'F')

  // "Asclepius" — left, bold
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.setTextColor(255, 255, 255)
  doc.text('Asclepius', MARGIN, 11.5)

  // subtitle — right, normal
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text(subtitle, PAGE_W - MARGIN, 11.5, { align: 'right' })
}

function drawFooter(doc) {
  const text = `Generated by Asclepius · ${today()} · For personal reference only.`
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.5)
  doc.setTextColor(150, 150, 150)
  doc.text(text, PAGE_W / 2, PAGE_H - 10, { align: 'center' })
}

/** Draws a section heading with a rule underneath; returns the next y position. */
function sectionHeading(doc, label, y) {
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(29, 64, 156)
  doc.text(label.toUpperCase(), MARGIN, y)

  doc.setDrawColor(29, 64, 156)
  doc.setLineWidth(0.3)
  doc.line(MARGIN, y + 1.5, PAGE_W - MARGIN, y + 1.5)

  return y + 7  // heading + rule + gap
}

/** Draws a label+value row; returns the next y position (accounts for wrapping). */
function drawRow(doc, label, value, y) {
  const maxValueW = PAGE_W - MARGIN - VALUE_X   // ~110mm
  const safeValue = value != null ? String(value) : '—'
  const lines     = doc.splitTextToSize(safeValue, maxValueW)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)

  // Label — right-aligned, muted
  doc.setTextColor(102, 102, 102)  // #666666
  doc.text(label, LABEL_X, y, { align: 'right' })

  // Value — left-aligned, dark
  doc.setTextColor(48, 48, 48)     // #303030
  doc.text(lines, VALUE_X, y)

  return y + Math.max(1, lines.length) * ROW_H
}

// ── Public API ─────────────────────────────────────────────────────────────────

/**
 * Generates and downloads a patient-facing appointment PDF.
 * @param {object} appointment — full appointment object from the API (_serialize shape)
 */
export function generatePatientAppointmentPDF(appointment) {
  const doc = makeDoc()
  const appt = appointment
  const { clinician, slot } = appt

  drawHeader(doc, 'Appointment Record')

  let y = 32  // first content line below the 18mm header

  // ── Clinician ──────────────────────────────────────────────────────────────
  y = sectionHeading(doc, 'Clinician', y)
  const docName = `${clinician.title ?? ''} ${clinician.first_name} ${clinician.last_name}`.trim()
  y = drawRow(doc, 'Doctor',    docName,            y)
  y = drawRow(doc, 'Specialty', clinician.specialty, y)
  y = drawRow(doc, 'Room',      clinician.room_number, y)
  y += 5

  // ── Appointment ───────────────────────────────────────────────────────────
  y = sectionHeading(doc, 'Appointment', y)
  y = drawRow(doc, 'Date',              formatDate(slot.slot_date),         y)
  y = drawRow(doc, 'Time',              formatTime(slot.start_time),        y)
  y = drawRow(doc, 'Consultation Type', consultType(appt.consultation_type), y)
  y = drawRow(doc, 'Chief Complaint',   appt.chief_complaint,               y)
  if (appt.chief_complaint_description) {
    y = drawRow(doc, 'Description', appt.chief_complaint_description, y)
  }
  y = drawRow(doc, 'Payment', appt.payment_type, y)
  y = drawRow(doc, 'Status',  statusLabel(appt.status), y)
  y += 5

  // ── Reschedule (conditional) ───────────────────────────────────────────────
  if (appt.reschedule_reason) {
    y = sectionHeading(doc, 'Reschedule', y)
    y = drawRow(doc, 'Reason', appt.reschedule_reason, y)
  }

  drawFooter(doc)

  doc.save(`appointment-${appt.appointment_id}-${slot.slot_date}.pdf`)
}

/**
 * Generates and downloads a staff-facing appointment PDF.
 * @param {object} appointment — full appointment object from the API (_serialize shape)
 */
export function generateStaffAppointmentPDF(appointment) {
  const doc = makeDoc()
  const appt = appointment
  const { clinician, slot } = appt
  const patient = appt.patient ?? {}

  drawHeader(doc, 'Appointment Record — Staff View')

  let y = 32

  // ── Patient ───────────────────────────────────────────────────────────────
  y = sectionHeading(doc, 'Patient', y)
  const patientName = patient.last_name && patient.first_name
    ? `${patient.last_name}, ${patient.first_name}`
    : `${patient.first_name ?? ''} ${patient.last_name ?? ''}`.trim() || '—'
  y = drawRow(doc, 'Name', patientName, y)
  y += 5

  // ── Clinician ──────────────────────────────────────────────────────────────
  y = sectionHeading(doc, 'Clinician', y)
  const docName = `${clinician.title ?? ''} ${clinician.first_name} ${clinician.last_name}`.trim()
  y = drawRow(doc, 'Doctor',    docName,               y)
  y = drawRow(doc, 'Specialty', clinician.specialty,   y)
  y = drawRow(doc, 'Room',      clinician.room_number, y)
  y += 5

  // ── Appointment ───────────────────────────────────────────────────────────
  y = sectionHeading(doc, 'Appointment', y)
  y = drawRow(doc, 'Date',              formatDate(slot.slot_date),          y)
  y = drawRow(doc, 'Time',              formatTime(slot.start_time),         y)
  y = drawRow(doc, 'Consultation Type', consultType(appt.consultation_type), y)
  y = drawRow(doc, 'Chief Complaint',   appt.chief_complaint,                y)
  if (appt.chief_complaint_description) {
    y = drawRow(doc, 'Description', appt.chief_complaint_description, y)
  }
  y = drawRow(doc, 'Payment', appt.payment_type,        y)
  y = drawRow(doc, 'Status',  statusLabel(appt.status), y)
  y += 5

  // ── Reschedule (conditional) ───────────────────────────────────────────────
  if (appt.reschedule_reason) {
    y = sectionHeading(doc, 'Reschedule', y)
    drawRow(doc, 'Reason', appt.reschedule_reason, y)
  }

  drawFooter(doc)

  const patientLast = (patient.last_name ?? 'unknown').toLowerCase().replace(/\s+/g, '-')
  doc.save(`appt-${appt.appointment_id}-${patientLast}.pdf`)
}
