import { jsPDF } from 'jspdf'

// ── Layout constants ───────────────────────────────────────────────────────────

const PAGE_W       = 210   // A4 width mm
const PAGE_H       = 297   // A4 height mm
const MARGIN       = 20    // left/right margin mm

// Two-column grid: left col 20–104, gap, right col 112–190
const COL1_X       = 20
const COL2_X       = 112
const COL1_LABEL_X = 55    // col 1 label right-aligned to x=55
const COL1_VALUE_X = 58    // col 1 value left-aligned from x=58
const COL1_VALUE_W = 46    // col 1 value max width (COL2_X - 8 - COL1_VALUE_X)
const COL2_LABEL_X = 148   // col 2 label right-aligned to x=148
const COL2_VALUE_X = 151   // col 2 value left-aligned from x=151
const COL2_VALUE_W = 39    // col 2 value max width (PAGE_W - MARGIN - COL2_VALUE_X)
const ROW_H        = 8     // mm per body row

// Brand colours (RGB)
const PRIMARY = [29, 64, 156]   // #1D409C
const DARK    = [48, 48, 48]    // #303030
const MUTED   = [102, 102, 102] // #666666
const RULE    = [180, 180, 180] // divider line

// ── Data helpers ──────────────────────────────────────────────────────────────

function consultType(raw) {
  if (raw === 'f2f')         return 'Face-to-Face'
  if (raw === 'teleconsult') return 'Telemedicine'
  return raw ?? '—'
}

function formatDate(dateStr) {
  if (!dateStr) return '—'
  const MONTHS = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
  ]
  const [y, mo, d] = dateStr.split('-').map(Number)
  return `${String(d).padStart(2, '0')} ${MONTHS[mo - 1]} ${y}`
}

function formatTime(timeStr) {
  if (!timeStr) return '—'
  const [h, m] = timeStr.split(':')
  const hour   = parseInt(h, 10)
  const period = hour >= 12 ? 'PM' : 'AM'
  const h12    = hour % 12 || 12
  return `${h12}:${m} ${period}`
}

function capitalize(s) {
  if (!s) return '—'
  return s.charAt(0).toUpperCase() + s.slice(1).replace(/_/g, ' ')
}

function paymentStatusLabel(ps) {
  if (ps === 'paid')   return 'Paid'
  if (ps === 'unpaid') return 'Unpaid'
  return null
}

function today() {
  const now = new Date()
  return formatDate(
    `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`
  )
}

// ── PDF primitives ─────────────────────────────────────────────────────────────

function makeDoc() {
  return new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
}

/**
 * Minimal header — institution name in primary blue, thin rule, no filled block.
 * Returns the y coordinate of the first content line.
 */
function drawHeader(doc, title, refId) {
  // Institution wordmark
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(15)
  doc.setTextColor(...PRIMARY)
  doc.text('Unicorn', MARGIN, 17)

  // Document title — muted, right-aligned
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(...MUTED)
  doc.text(title, PAGE_W - MARGIN, 13, { align: 'right' })

  // Reference number
  if (refId) {
    doc.setFontSize(9)
    doc.text(`Ref: #${refId}`, PAGE_W - MARGIN, 20, { align: 'right' })
  }

  // Thin primary separator
  doc.setDrawColor(...PRIMARY)
  doc.setLineWidth(0.5)
  doc.line(MARGIN, 24, PAGE_W - MARGIN, 24)

  return 33  // first content y
}

/**
 * Footer: thin rule + disclaimer text at bottom of page.
 */
function drawFooter(doc) {
  const lineY = PAGE_H - 16
  doc.setDrawColor(...RULE)
  doc.setLineWidth(0.3)
  doc.line(MARGIN, lineY, PAGE_W - MARGIN, lineY)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8.5)
  doc.setTextColor(...MUTED)
  doc.text(
    'This document was generated by Project U. For inquiries please contact the clinic directly.',
    PAGE_W / 2,
    PAGE_H - 10,
    { align: 'center' }
  )
}

/**
 * Section heading with primary-coloured rule underneath.
 * col: 1 (left) or 2 (right). Returns next y.
 */
function sectionHeading(doc, label, y, col = 1) {
  const x    = col === 1 ? COL1_X     : COL2_X
  const endX = col === 1 ? COL2_X - 8 : PAGE_W - MARGIN

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(...PRIMARY)
  doc.text(label.toUpperCase(), x, y)

  doc.setDrawColor(...PRIMARY)
  doc.setLineWidth(0.3)
  doc.line(x, y + 2, endX, y + 2)

  return y + 9
}

/**
 * Standard label+value row at 11pt. col 1 or 2. Returns next y.
 */
function drawRow(doc, label, value, y, col = 1) {
  const labelX = col === 1 ? COL1_LABEL_X : COL2_LABEL_X
  const valueX = col === 1 ? COL1_VALUE_X : COL2_VALUE_X
  const valueW = col === 1 ? COL1_VALUE_W : COL2_VALUE_W
  const safe   = value != null && value !== '' ? String(value) : '—'
  const lines  = doc.splitTextToSize(safe, valueW)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)

  doc.setTextColor(...MUTED)
  doc.text(label, labelX, y, { align: 'right' })

  doc.setTextColor(...DARK)
  doc.text(lines, valueX, y)

  return y + Math.max(1, lines.length) * ROW_H
}

/**
 * Prominent row at 13pt bold for key identifiers (names). Returns next y.
 */
function drawKeyRow(doc, label, value, y, col = 1) {
  const labelX = col === 1 ? COL1_LABEL_X : COL2_LABEL_X
  const valueX = col === 1 ? COL1_VALUE_X : COL2_VALUE_X
  const valueW = col === 1 ? COL1_VALUE_W : COL2_VALUE_W
  const safe   = value != null && value !== '' ? String(value) : '—'

  doc.setFontSize(13)
  const lines = doc.splitTextToSize(safe, valueW)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.setTextColor(...MUTED)
  doc.text(label, labelX, y, { align: 'right' })

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.setTextColor(...DARK)
  doc.text(lines, valueX, y)

  return y + Math.max(1, lines.length) * (ROW_H + 1)
}

// ── Public API ─────────────────────────────────────────────────────────────────

/**
 * Generates and downloads a patient-facing appointment PDF.
 * Layout: Appointment details (left col) | Clinician (right col)
 * @param {object} appointment — full appointment object from the API (_serialize shape)
 */
export function generatePatientAppointmentPDF(appointment) {
  const doc  = makeDoc()
  const appt = appointment
  const { clinician, slot } = appt

  let y = drawHeader(doc, 'Appointment Record', appt.appointment_id)

  let yL = y   // left column y-cursor
  let yR = y   // right column y-cursor

  // ── Left: Appointment ─────────────────────────────────────────────────────
  yL = sectionHeading(doc, 'Appointment', yL, 1)
  yL = drawRow(doc, 'Date',    formatDate(slot.slot_date),          yL, 1)
  yL = drawRow(doc, 'Time',    formatTime(slot.start_time),         yL, 1)
  yL = drawRow(doc, 'Type',    consultType(appt.consultation_type), yL, 1)
  yL += 6

  yL = sectionHeading(doc, 'Chief Complaint', yL, 1)
  yL = drawRow(doc, 'Complaint', appt.chief_complaint, yL, 1)
  if (appt.chief_complaint_description) {
    yL = drawRow(doc, 'Details', appt.chief_complaint_description, yL, 1)
  }
  yL += 6

  yL = sectionHeading(doc, 'Payment & Status', yL, 1)
  yL = drawRow(doc, 'Payment', appt.payment_type, yL, 1)
  if (appt.discount_type) {
    yL = drawRow(doc, 'Discount', appt.discount_type, yL, 1)
  }
  yL = drawRow(doc, 'Status', capitalize(appt.status), yL, 1)
  if (appt.decline_reason) {
    yL = drawRow(doc, 'Reason', appt.decline_reason, yL, 1)
  }

  if (appt.reschedule_reason) {
    yL += 6
    yL = sectionHeading(doc, 'Reschedule Note', yL, 1)
    yL = drawRow(doc, 'Reason', appt.reschedule_reason, yL, 1)
  }

  // ── Right: Clinician ──────────────────────────────────────────────────────
  yR = sectionHeading(doc, 'Clinician', yR, 2)
  const docName = [clinician.title, clinician.first_name, clinician.last_name]
    .filter(Boolean).join(' ')
  yR = drawKeyRow(doc, 'Name',      docName,               yR, 2)
  yR = drawRow(doc,    'Specialty', clinician.specialty,   yR, 2)
  yR = drawRow(doc,    'Room',      clinician.room_number, yR, 2)

  drawFooter(doc)
  doc.save(`appointment-${appt.appointment_id}-${slot.slot_date}.pdf`)
}

/**
 * Generates and downloads a staff-facing appointment PDF.
 * Layout: Appointment (left col) | Patient + Clinician stacked (right col)
 * @param {object} appointment — full appointment object from the API (_serialize shape)
 */
export function generateStaffAppointmentPDF(appointment) {
  const doc     = makeDoc()
  const appt    = appointment
  const { clinician, slot } = appt
  const patient = appt.patient ?? {}

  let y = drawHeader(doc, 'Appointment Record — Staff View', appt.appointment_id)

  let yL = y
  let yR = y

  // ── Left: Appointment ─────────────────────────────────────────────────────
  yL = sectionHeading(doc, 'Appointment', yL, 1)
  yL = drawRow(doc, 'Date',    formatDate(slot.slot_date),          yL, 1)
  yL = drawRow(doc, 'Time',    formatTime(slot.start_time),         yL, 1)
  yL = drawRow(doc, 'Type',    consultType(appt.consultation_type), yL, 1)
  yL += 6

  yL = sectionHeading(doc, 'Chief Complaint', yL, 1)
  yL = drawRow(doc, 'Complaint', appt.chief_complaint, yL, 1)
  if (appt.chief_complaint_description) {
    yL = drawRow(doc, 'Details', appt.chief_complaint_description, yL, 1)
  }
  yL += 6

  yL = sectionHeading(doc, 'Payment & Status', yL, 1)
  yL = drawRow(doc, 'Payment', appt.payment_type, yL, 1)
  if (appt.discount_type) {
    yL = drawRow(doc, 'Discount', appt.discount_type, yL, 1)
  }
  const psLabel = paymentStatusLabel(appt.payment_status)
  if (psLabel) {
    yL = drawRow(doc, 'Paid?', psLabel, yL, 1)
  }
  yL = drawRow(doc, 'Status', capitalize(appt.status), yL, 1)
  if (appt.decline_reason) {
    yL = drawRow(doc, 'Reason', appt.decline_reason, yL, 1)
  }

  if (appt.reschedule_reason) {
    yL += 6
    yL = sectionHeading(doc, 'Reschedule Note', yL, 1)
    yL = drawRow(doc, 'Reason', appt.reschedule_reason, yL, 1)
  }

  // ── Right: Patient ────────────────────────────────────────────────────────
  yR = sectionHeading(doc, 'Patient', yR, 2)
  const patientName = patient.last_name && patient.first_name
    ? `${patient.last_name}, ${patient.first_name}`
    : `${patient.first_name ?? ''} ${patient.last_name ?? ''}`.trim() || '—'
  yR = drawKeyRow(doc, 'Name', patientName, yR, 2)
  yR += 8

  // ── Right: Clinician ──────────────────────────────────────────────────────
  yR = sectionHeading(doc, 'Clinician', yR, 2)
  const docName = [clinician.title, clinician.first_name, clinician.last_name]
    .filter(Boolean).join(' ')
  yR = drawKeyRow(doc, 'Name',      docName,               yR, 2)
  yR = drawRow(doc,    'Specialty', clinician.specialty,   yR, 2)
  yR = drawRow(doc,    'Room',      clinician.room_number, yR, 2)

  drawFooter(doc)

  const patientLast = (patient.last_name ?? 'unknown').toLowerCase().replace(/\s+/g, '-')
  doc.save(`appt-${appt.appointment_id}-${patientLast}.pdf`)
}
