"""add additional_request to appointment

Revision ID: 10721aaa6261
Revises: f87f0737f4a8
Create Date: 2026-08-28 05:41:14.491193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10721aaa6261'
down_revision = 'f87f0737f4a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_request', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('additional_request')

    # ### end Alembic commands ###
