"""initial

Revision ID: 59b8bcbc3cae
Revises: 
Create Date: 2026-03-26 18:08:32.346367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b8bcbc3cae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinician',
    sa.Column('clinician_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('suffix', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('specialty', sa.String(length=150), nullable=True),
    sa.Column('local_number', sa.String(length=20), nullable=True),
    sa.Column('room_number', sa.String(length=50), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('login_email', sa.String(length=200), nullable=False),
    sa.Column('login_password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('clinician_id'),
    sa.UniqueConstraint('login_email')
    )
    op.create_table('patient',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('civil_status', sa.String(length=30), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('religion', sa.String(length=100), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('mobile_number', sa.String(length=30), nullable=False),
    sa.Column('next_of_kin_name', sa.String(length=200), nullable=True),
    sa.Column('next_of_kin_relationship', sa.String(length=100), nullable=True),
    sa.Column('next_of_kin_contact', sa.String(length=30), nullable=True),
    sa.Column('address_line_1', sa.String(length=300), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('barangay', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('login_email', sa.String(length=200), nullable=False),
    sa.Column('login_password_hash', sa.String(length=256), nullable=False),
    sa.Column('sc_pwd_id_number', sa.String(length=100), nullable=True),
    sa.Column('pwd_id_front', sa.String(length=500), nullable=True),
    sa.Column('pwd_id_back', sa.String(length=500), nullable=True),
    sa.Column('preferred_language', sa.String(length=50), nullable=False),
    sa.Column('culture', sa.String(length=100), nullable=True),
    sa.Column('educational_attainment', sa.String(length=100), nullable=False),
    sa.Column('disability_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('login_email')
    )
    op.create_table('secretary',
    sa.Column('secretary_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('suffix', sa.String(length=20), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('login_email', sa.String(length=200), nullable=False),
    sa.Column('login_password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('secretary_id'),
    sa.UniqueConstraint('login_email')
    )
    op.create_table('clinician_hmo',
    sa.Column('hmo_id', sa.Integer(), nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=False),
    sa.Column('hmo_name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['clinician.clinician_id'], ),
    sa.PrimaryKeyConstraint('hmo_id')
    )
    op.create_table('clinician_info',
    sa.Column('info_id', sa.Integer(), nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['clinician_id'], ['clinician.clinician_id'], ),
    sa.PrimaryKeyConstraint('info_id')
    )
    op.create_table('clinician_schedule',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('am_start', sa.Time(), nullable=True),
    sa.Column('am_end', sa.Time(), nullable=True),
    sa.Column('pm_start', sa.Time(), nullable=True),
    sa.Column('pm_end', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['clinician_id'], ['clinician.clinician_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_table('clinician_timeslot',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('max_patients', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinician_id'], ['clinician.clinician_id'], ),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_table('secretary_clinician',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secretary_id', sa.Integer(), nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['clinician.clinician_id'], ),
    sa.ForeignKeyConstraint(['secretary_id'], ['secretary.secretary_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('consultation_date', sa.Date(), nullable=False),
    sa.Column('chief_complaint', sa.String(length=300), nullable=True),
    sa.Column('chief_complaint_description', sa.Text(), nullable=True),
    sa.Column('payment_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reschedule_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['clinician.clinician_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['clinician_timeslot.slot_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.drop_table('secretary_clinician')
    op.drop_table('clinician_timeslot')
    op.drop_table('clinician_schedule')
    op.drop_table('clinician_info')
    op.drop_table('clinician_hmo')
    op.drop_table('secretary')
    op.drop_table('patient')
    op.drop_table('clinician')
    # ### end Alembic commands ###
