"""add consultation_type

Revision ID: 661b787df75f
Revises: 4da00536f0ca
Create Date: 2026-03-29 12:57:08.997798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661b787df75f'
down_revision = '4da00536f0ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consultation_type', sa.String(), server_default='f2f', nullable=False))

    with op.batch_alter_table('clinician_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consultation_type', sa.String(), server_default='f2f', nullable=False))

    with op.batch_alter_table('clinician_timeslot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consultation_type', sa.String(), server_default='f2f', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinician_timeslot', schema=None) as batch_op:
        batch_op.drop_column('consultation_type')

    with op.batch_alter_table('clinician_schedule', schema=None) as batch_op:
        batch_op.drop_column('consultation_type')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('consultation_type')

    # ### end Alembic commands ###
