"""add cancellation_reason to appointment

Revision ID: a3467c5a8499
Revises: dd76985c139d
Create Date: 2026-08-26 08:29:27.556365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3467c5a8499'
down_revision = 'dd76985c139d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('cancellation_reason')

    # ### end Alembic commands ###
