"""add unique constraint on secretary_clinician

Revision ID: dd76985c139d
Revises: e8b232350ec4
Create Date: 2026-08-25 16:12:37.662049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd76985c139d'
down_revision = 'e8b232350ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secretary_clinician', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_secretary_clinician', ['secretary_id', 'clinician_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secretary_clinician', schema=None) as batch_op:
        batch_op.drop_constraint('uq_secretary_clinician', type_='unique')

    # ### end Alembic commands ###
