"""add professional_fee to clinician and appointment

Revision ID: f87f0737f4a8
Revises: a3467c5a8499
Create Date: 2026-08-28 05:40:48.581769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87f0737f4a8'
down_revision = 'a3467c5a8499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professional_fee', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('clinician', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professional_fee', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinician', schema=None) as batch_op:
        batch_op.drop_column('professional_fee')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('professional_fee')

    # ### end Alembic commands ###
