version: "3.9"

services:
  a-mmc-frontend:
    image: "${FRONTEND_IMAGE}"
    container_name: "${FRONTEND_CONTAINER}"
    networks:
      - a-mmc-network
    depends_on:
      a-mmc-backend:
        condition: service_healthy

  a-mmc-backend:
    image: "${BACKEND_IMAGE}"
    container_name: "${BACKEND_CONTAINER}"
    networks:
      - a-mmc-network
    
    #### FOR DEV ONLY - MOUNT MIGRATIONS, REMOVE IN PRODUCTION
    volumes:
      - ../a-mmc_backend/migrations:/app/migrations
    ####
    env_file:
      - ../a-mmc_backend/.env
    depends_on:
      a-mmc-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${BACKEND_PORT}/api/health || exit 1"]
      interval: ${CONTAINER_INTERVAL}
      timeout: ${CONTAINER_TIMEOUT}
      retries: ${CONTAINER_RETRIES}
      start_period: 20s

  a-mmc-nginx:
    image: "${NGINX_IMAGE}"
    container_name: "${NGINX_CONTAINER}"
    ports:
      - "${NGINX_HTTP_PORT}:${NGINX_HTTP_PORT}"
      - "${NGINX_HTTPS_PORT}:${NGINX_HTTPS_PORT}"
    networks:
      - a-mmc-network
    volumes:
      # nginx.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      a-mmc-frontend:
        condition: service_healthy
      a-mmc-backend:
        condition: service_healthy

  a-mmc-postgres:
    image: "${POSTGRES_IMAGE}"
    container_name: "${POSTGRES_CONTAINER}"
    networks:
      - a-mmc-network
    env_file:
      - ../a-mmc_backend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "${POSTGRES_DATA_VOLUME}:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1' || exit 1"]
      interval: ${CONTAINER_INTERVAL}
      timeout: ${CONTAINER_TIMEOUT}
      retries: ${CONTAINER_RETRIES}
      start_period: 20s

networks:
  a-mmc-network:
    driver: bridge

volumes:
  a-mmc-postgres-data:
      driver: local

