events {}

http {
   #  map $http_upgrade $connection_upgrade {
   #      default upgrade;
   #      ''      close;
   #  }

   #  upstream grafana_backend {
   #      server {{ logging_name }}:3000;
   #  }
    server {
       listen       80;
      #  server_name  {{ hostname }};
      #  return 301   https://{{ hostname }}$request_uri;

       location / {
        proxy_pass http://a-mmc-frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
       }

      location /api/ {
        proxy_pass http://a-mmc-backend:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }

   # server {
   #    listen 443 ssl;
   #    server_name {{ hostname }};
   #    # ssl_certificate     /etc/nginx/ssl/certs/ssl.crt;
   #    # ssl_certificate_key /etc/nginx/ssl/certs/ssl.key;
   #    ssl_certificate     ./certs/ssl.crt;
   #    ssl_certificate_key ./certs/ssl.key;
   #    ssl_protocols       TLSv1.3;

   #    location / {
   #      proxy_pass http://a-mmc-frontend:3000;
   #      proxy_set_header Host $host;
   #      proxy_set_header X-Real-IP $remote_addr;
   #      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   #      proxy_set_header X-Forwarded-Proto $scheme;
   #     }

   #    location /api/ {
   #      proxy_pass http://a-mmc-backend:5000;
   #      proxy_set_header Host $host;
   #      proxy_set_header X-Real-IP $remote_addr;
   #      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   #      proxy_set_header X-Forwarded-Proto $scheme;
   #    }
   # }
}