name: CI on Frontend Folder

on:
  push:
    branches:
      - main
    paths:
      - 'a-mmc_frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run build if changes detected
        run: |
          echo "FRONTEND Changes detected in src or config folder. Running the build process."
          # Your build commands go here (e.g., npm ci, npm run build)
