name: CI on Frontend Folder

on:
  push:
    branches:
      - main
    paths:
      - 'a-mmc_frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run build if changes detected
        run: |
          echo "FRONTEND Changes detected in src or config folder. Running the build process."
          # Your build commands go here (e.g., npm ci, npm run build)

      - name: Build Docker Image
        run:  docker build ./a-mmc_frontend/ -t krispybata/a-mmc-frontend:latest
        
      - name: Push Docker Image to Docker Hub
        run:  docker push krispybata/a-mmc-frontend:latest